### ISSUE TITLE
Default server renders incorrectly

### ISSUE THREAD

**Issue by xgp** [cloud-annotations/docusaurus-openapi#228]
My openapi spec file: https://github.com/p2-inc/phasetwo-docs/blob/master/openapi.yaml
The result: https://phasetwo.io/api

For example in this page https://phasetwo.io/api/get-organizations the server section doesn't render with the defaults, and the values are `undefined` in the curl/code examples:
![image](https://user-images.githubusercontent.com/244253/202806703-afaf8f65-d0b9-4747-993f-f78447d13904.png)

But renders correctly when you expand the server section and select an option:
![image](https://user-images.githubusercontent.com/244253/202806860-efa13ddc-dab4-4797-8669-df8aa14e1812.png)

Here is the relevant part of the openapi spec:
```yaml
servers:
  - url: '{protocol}://{host}{port}/auth/realms'
    variables:
      host:
        enum:
          - app.phasetwo.io
          - localhost
        default: app.phasetwo.io
        description: API host
      port:
        enum:
          - ''
          - '8081'
        default: ''
        description: API port
      protocol:
        enum:
          - http
          - https
        default: https
```
